name: ${project.name}
version: ${project.version}
main: ${groupId}.${artifactId}
api-version: '1.21'
authors: [euj3ne]
description: ${project.description}
website: ${project.url}
depend: []
softdepend: []
